### PR TITLE
Refactored Bag to class to use builder pattern.

### PR DESCRIPTION
**Pull request by bhimak**
### Please ensure you have completed the following before submitting:
- Ran `gradle clean check` to ensure existing functionality wasn't broken and code meets quality standards.

If the build fails, please fix it because the pull request will not be merged until it builds without any errors.

### CODE REVIEW

**Comment by jscancella** [comment]
@bhimak, why did you close this? Is it not ready yet?

**Comment by bhimak** [comment]
@jscancella I didn't notice the failures in the integration tests after refactoring the code. I am working through updating those as well. The code in the integration tests is tightly coupled with the current implementation of the Bag class. I might have to make major changes to address the failures.

**Comment by jscancella** [comment]
@bhimak not sure what you mean by being tighly coupled, the integration tests are there to ensure the bagit spec is followed and to guard against known issues. That is why we have the bagit-conformance suite, to be able to test against all those issues.

**Comment by bhimak** [comment]
@jscancella com.github.jscancella.reader.internal.ManifestReader.readAllManifests(Path, Bag) has logic to add manifest to the Bag by calling getTagManifests(). Part of my changes was to return an immutable collection when getTagManifests() is called. I have to update the current code to work with my changes. I am concerned about this non-passive change since the given Bag object will not have the updated manifest information.

**Comment by jscancella** [comment]
Now that we have a builder, we should be passing that around and not the bag object. We should then do `builder.build()` at the end of the public method to return the built up bag object.

In other words (pseudocode):
```
BagReader.read(Path p){
    final BagBuilder builder = Bag.instanceOfBagBuilder();

    final Path bagitFile = bagDirectory.resolve("bagit.txt");
    final SimpleImmutableEntry<Version, Charset> bagitInfo = BagitTextFileReader.readBagitTextFile(bagitFile);

    builder.setVersion(bagitInfo.getKey());
    builder.setFileEncoding(bagitInfo.getValue());
    builder.setRootDir(bagDirectory);
    
    ManifestReader.readAllManifests(bagDirectory, builder);
    
    builder.AddMetadata(MetadataReader.readBagMetadata(bagDirectory, builder.getFileEncoding()));
    
    final Path fetchFile = bagDirectory.resolve("fetch.txt");
    if(Files.exists(fetchFile)){
      builder.AddFetch((FetchReader.readFetch(fetchFile, builder.getFileEncoding(), bagDirectory));
    }
}
```

**Comment by bhimak** [comment]
@jscancella  I am not sure why the two integration tests are failing. Can you please provide more insight into the error messages?

**Comment by jscancella** [comment]
@bhimak `bagit-conformance-suite/v1.0/invalid/notAllManifestsListAllFiles should have failed but didn't!` As of version 1.0, the bagit specification says that all manifests must list all files. This test fails when you have more than one manifest and each one does not list all files in the payload directory.

`testReadWriteProducesSameBag() - com.github.jscancella.BagitSuiteComplanceTest` when you read a bag and then write it back out, it should produce the same files identically. This test fails when files change between reading and writing it back out to the filesystem.

I also created https://github.com/jscancella/bagging/issues/10 to help in the future for developers.

**Comment by bhimak** [comment]
@jscancella I am having a hard time running the tests from eclipse. I am running into build problems where sometimes eclipse can't build the project or some other gradle related issues. I think a guide that lists out how to set up the workspace to get everything running on a local machine would be helpful. Do you have any documentation that I can use to get all the tests to run?

**Comment by jscancella** [comment]
@bhimak take a look at https://github.com/jscancella/bagging#technical-reference.
I never run gradle from eclipse as all the CI runs it from commandline and I want to be consistent with my CI servers.

**Comment by jscancella** [comment]
@bhimak are you still working on this? I think this is good work, it just needs some polishing. However, I understand if you have moved on to other projects. In that case I would close this PR so that someone else doesn't think you still own it.

**Comment by bhimak** [comment]
@jscancella I apologize for the delay. I have been busy with work. I will try to update this PR soon and hopefully close this task.

**Comment by bhimak** [comment]
@jscancella  How did I trigger circleci build manually?

**Comment by jscancella** [comment]
It will trigger automatically once you push an update to your git repo.

**Comment by jscancella** [comment]
@bhimak it might help to look at https://github.com/jscancella/bagging/tree/builder where I started doing the work of converting to immutable domain objects and using the builder pattern. Take a look at the `TODO` in the classes and they detail what still needs to be implemented.

**Comment by jscancella** [comment]
duplicate of #29

**Pull request closed without merging**
