### PR TITLE
Unicode-normalize manifest and file paths before comparing

### LINKED ISSUE #70: Accented character in filename prevents payload verification on macOS
## Steps to reproduce

1. create a bag containing a filename with an accented character, e.g. `contrôle.txt`.
2. read the bag with `Bag.read()`.
3. call `bag.isValid()` (`ignoreHiddenFiles` can be true or false, doesn't matter).

## Expected behavior

- `isValid()` returns true

## Actual behavior

- `isValid()` throws `FileNotInManifestException`
  - cf. https://github.com/LibraryOfCongress/bagit-java/issues/140.

## System information

- `bagging` version: 4.4
- OS: macOS 12.6.1 Monterey
- Java version: OpenJDK Runtime Environment Zulu17.30+15-CA (build 17.0.1+12-LTS)

## Notes

It looks like this may be a [long-standing Java / macOS issue](https://mail.openjdk.org/pipermail/openjfx-dev/2015-April/017183.html) to do with how HFS+ does Unicode normalization.

If `toString()` conversion seems too risky, an alternative would be to compare the paths with `Files.isSameFile(Path, Path)`, which does seem to admit they're the same. I'll see if I can create a PR.

### PR DESCRIPTION
**Pull request by dmoles**
When checking whether a path exists in the manifest, uses the the same normalization rules as in `ManifestVerifier.existsNormalized()` to normalize paths before comparison.

Fixes #70.

### CODE REVIEW

**Comment by jscancella** [comment]
You should create a test case for this in https://github.com/LibraryOfCongress/bagit-conformance-suite/tree/master/v0.97 probably under `MacOS` since this is specific to how Mac normalizes filesystem file names.

**Comment by jscancella** [comment]
Thank you for the pull request! I am ready to merge this as soon as you add to the https://github.com/jscancella/bagging/tree/master/developer%20certificates

**Comment by dmoles** [comment]
@jscancella I've added my DCO to the PR. Sorry for the delay.

**Comment by dmoles** [comment]
I also added a test case (`bagit.py` passes, yay) to the conformance suite: https://github.com/LibraryOfCongress/bagit-conformance-suite/pull/15

**Pull request merged**
